export const Items = {
  key: {
    id: "key",
    name: "钥匙",
    emoji: "🔑",
    shape: [[1]],
    width: 1,
    height: 1,
    noover: false,
    noexposed: true,
    edge: false,
    rotatable: true,
    score: 12,
  },
  egg: {
    id: "egg",
    name: "鸡蛋",
    emoji: "🥚",
    shape: [[1]],
    width: 1,
    height: 1,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 12,
  },
  candy: {
    id: "candy",
    name: "棒棒糖",
    emoji: "🍭",
    shape: [[1], [1]],
    width: 1,
    height: 2,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 20,
  },
  orange: {
    id: "orange",
    name: "橙子",
    emoji: "🍊",
    shape: [[1, 1]],
    width: 2,
    height: 1,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 22,
  },
  tissue: {
    id: "tissue",
    name: "纸巾",
    emoji: "🧻",
    shape: [[1], [1]],
    width: 1,
    height: 2,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 20,
  },
  milk: {
    id: "milk",
    name: "牛奶盒",
    emoji: "🥛",
    shape: [[1], [1]],
    width: 1,
    height: 2,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: false,
    score: 22,
  },
  apple: {
    id: "apple",
    name: "苹果",
    emoji: "🍎",
    shape: [
      [1, 1],
      [1, 1],
    ],
    width: 2,
    height: 2,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 40,
  },
  dried: {
    id: "dried",
    name: "蜜饯",
    emoji: "🍒",
    shape: [
      [1, 1],
      [1, 1],
    ],
    width: 2,
    height: 2,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 42,
  },
  watch: {
    id: "watch",
    name: "手表",
    emoji: "⌚",
    shape: [[1, 1]],
    width: 2,
    height: 1,
    noover: false,
    noexposed: true,
    edge: false,
    rotatable: true,
    score: 22,
  },
  wallet: {
    id: "wallet",
    name: "零钱包",
    emoji: "👛",
    shape: [[1, 1]],
    width: 2,
    height: 1,
    noover: false,
    noexposed: true,
    edge: false,
    rotatable: true,
    score: 22,
  },
  banana: {
    id: "banana",
    name: "香蕉",
    emoji: "🍌",
    shape: [[1, 1, 1]],
    width: 3,
    height: 1,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 32,
  },
  drink: {
    id: "drink",
    name: "瓶装饮料",
    emoji: "🧴",
    shape: [[1], [1], [1]],
    width: 1,
    height: 3,
    noover: false,
    noexposed: false,
    edge: true,
    rotatable: true,
    score: 32,
  },
  chips: {
    id: "chips",
    name: "薯片",
    emoji: "🥠",
    shape: [[1], [1], [1]],
    width: 1,
    height: 3,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 32,
  },
  mask: {
    id: "mask",
    name: "口罩",
    emoji: "😷",
    shape: [[1, 1, 1]],
    width: 3,
    height: 1,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 30,
  },
  sandwich: {
    id: "sandwich",
    name: "三明治",
    emoji: "🥪",
    shape: [
      [1, 1],
      [1, 1],
    ],
    width: 2,
    height: 2,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 42,
  },
  bread_1: {
    id: "bread_1",
    name: "面包片",
    emoji: "🍞",
    shape: [
      [1, 1],
      [1, 1],
    ],
    width: 2,
    height: 2,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 42,
  },
  burger: {
    id: "burger",
    name: "汉堡",
    emoji: "🍔",
    shape: [
      [1, 1],
      [1, 1],
    ],
    width: 2,
    height: 2,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 42,
  },
  hat: {
    id: "hat",
    name: "帽子",
    emoji: "🧢",
    shape: [
      [1, 1],
      [1, 1],
    ],
    width: 2,
    height: 2,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 40,
  },
  cup: {
    id: "cup",
    name: "水杯",
    emoji: "🥤",
    shape: [[1], [1], [1]],
    width: 1,
    height: 3,
    noover: false,
    noexposed: false,
    edge: true,
    rotatable: true,
    score: 34,
  },
  phone: {
    id: "phone",
    name: "手机",
    emoji: "📱",
    shape: [
      [1, 1],
      [1, 1],
      [1, 1],
    ],
    width: 2,
    height: 3,
    noover: false,
    noexposed: true,
    edge: false,
    rotatable: true,
    score: 62,
  },
  chicken: {
    id: "chicken",
    name: "鸡腿",
    emoji: "🍗",
    shape: [
      [1, 1, 1],
      [0, 1, 1],
    ],
    width: 3,
    height: 2,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 50,
  },
  sunglasses: {
    id: "sunglasses",
    name: "太阳镜",
    emoji: "🕶️",
    shape: [
      [1, 1, 1],
      [1, 1, 1],
    ],
    width: 3,
    height: 2,
    noover: true,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 62,
  },
  camera: {
    id: "camera",
    name: "相机",
    emoji: "📷",
    shape: [
      [1, 1, 1],
      [1, 1, 1],
    ],
    width: 3,
    height: 2,
    noover: false,
    noexposed: true,
    edge: false,
    rotatable: true,
    score: 62,
  },
  wing: {
    id: "wing",
    name: "鸡翅",
    emoji: "🍖",
    shape: [
      [1, 1, 1],
      [0, 0, 1],
      [0, 0, 1],
    ],
    width: 3,
    height: 3,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: true,
    score: 52,
  },
  bento: {
    id: "bento",
    name: "便当盒",
    emoji: "🍱",
    shape: [
      [1, 1, 1],
      [1, 1, 1],
      [1, 1, 1],
    ],
    width: 3,
    height: 3,
    noover: false,
    noexposed: false,
    edge: false,
    rotatable: false,
    score: 92,
  },
  umbrella: {
    id: "umbrella",
    name: "雨伞",
    emoji: "☂️",
    shape: [[1], [1], [1]],
    width: 1,
    height: 3,
    noover: false,
    noexposed: false,
    edge: true,
    rotatable: true,
    score: 32,
  },
};

export function rotateItem(item) {
  const shape = item.shape;
  const oldHeight = shape.length;
  const oldWidth = shape[0].length;
  const newWidth = oldHeight;
  const newHeight = oldWidth;

  const rotated = [];
  for (let y = 0; y < newHeight; y++) {
    rotated[y] = [];
    for (let x = 0; x < newWidth; x++) {
      rotated[y][x] = shape[oldHeight - 1 - x][y];
    }
  }

  return {
    ...item,
    shape: rotated,
    width: newWidth,
    height: newHeight,
  };
}

export function getItemById(id) {
  return Items[id] ? { ...Items[id] } : null;
}

export function getAllItemIds() {
  return Object.keys(Items);
}
